/**
 * An app that runs a command and watches it.
 *
 * The end-to-end half of basalt-subprocess: the unit tests in that
 * package cover the spawning, and this covers the part they cannot -- that a
 * capability package's TurboModule is reachable from JavaScript at all. That
 * path is generated by the build (see core/PackageModules.h) and nothing else
 * in this repository uses it.
 *
 * @format
 */

'use strict';

import * as React from 'react';
import {AppRegistry, Platform, StyleSheet, View} from 'react-native';
import {
  addExitListener,
  addOutputListener,
  isRunning,
  isSupported,
  spawn,
} from 'basalt-subprocess';

console.log(`Platform.OS is ${Platform.OS}`);

const styles = StyleSheet.create({
  page: {flex: 1, backgroundColor: '#11131a', padding: 24},
  pip: {width: 28, height: 28, borderRadius: 14, backgroundColor: '#56c98a'},
});

function App() {
  const [done, setDone] = React.useState(false);

  React.useEffect(() => {
    console.log(`subprocess: supported ${isSupported()}`);
    const output = [];
    const gotOutput = addOutputListener(event => {
      output.push(`${event.stream}:${event.data.trim()}`);
    });
    const gotExit = addExitListener(event => {
      console.log(`subprocess: exitPid ${event.pid > 0}`);
      console.log(`subprocess: code ${event.code}`);
      console.log(`subprocess: output ${JSON.stringify(output.join('|'))}`);
      console.log(`subprocess: runningAfter ${isRunning(event.pid)}`);
      setDone(true);
    });

    (async () => {
      try {
        const pid = await spawn({
          // Spelled for both shells: `echo` and a variable reference are the
          // only two things this needs, and the variable is passed rather than
          // written into the command for the reason the package's header gives.
          command: Platform.OS === 'windows' ? 'echo %BASALT_GREETING%' : 'echo $BASALT_GREETING',
          env: {BASALT_GREETING: 'hello-from-a-subprocess'},
        });
        console.log(`subprocess: spawned ${pid > 0}`);
        console.log(`subprocess: runningBefore ${isRunning(pid)}`);
      } catch (error) {
        console.log(`subprocess: spawn threw ${error.message}`);
        setDone(true);
      }
    })();

    return () => {
      gotOutput.remove();
      gotExit.remove();
    };
  }, []);

  return (
    <View style={styles.page}>{done ? <View style={styles.pip} /> : null}</View>
  );
}

AppRegistry.registerComponent('BasaltSubprocess', () => App);
